- hosts: all
  connection: local
  gather_facts: no 
  roles:
    - juniper.junos
  tasks:
    - name: STEP1_Generate Credential
      set_fact: #module 
        credential: #login to device
          username: "{{ juniper_user }}"
          password: "{{ juniper_password }}"
          host: "{{ '{{' }} ansible_host {{ '}}' }}"    
        delegate_to: localhost

    - name: STEP2_Show configure all device
      juniper_junos_command: 
        provider: "{{ credential }}"     
        commands:
          - show configuration system 
        format: xml
        dest: "/tmp/{{ inventory_hostname }}.commands.output"

    - name: STEP3_Template a file
      ansible.builtin.template:
        src: /root/template/configscript1.j2
        dest: /root/template/script1_{{ inventory_hostname }}.conf

    - name: STEP4_SRX config_test
      juniper_junos_config:
        config_mode: 'private' #Open a candidate configuration database
        load: 'set' #configuration data into the candidate configuration database.
        diff: true
        commit: true
        src: "/root/template/script1_{{ inventory_hostname }}.conf"
        provider: "{{ credential }}"
        comment: 'config SRX'
        confirmed: true
        retrieve: 'committed'

    - name: STEP5_SRX config
      juniper_junos_config:
        config_mode: 'private' #Open a candidate configuration database
        load: 'set' #configuration data into the candidate configuration database.
        diff: false
        commit: true
        src: "/root/template/script1_{{ inventory_hostname }}.conf"
        provider: "{{ credential }}"
        comment: 'config SRX'
        retrieve: 'committed'

  
        

 




